// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCRyrgYVvfPqfZ8xYlZKIdQHbrUXCGzIo',
    appId: '1:1092045970347:web:e8d71fcbfe63024777d0ee',
    messagingSenderId: '1092045970347',
    projectId: 'attendance-36f66',
    authDomain: 'attendance-36f66.firebaseapp.com',
    storageBucket: 'attendance-36f66.appspot.com',
    measurementId: 'G-1NJ7HK7E86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgAALT1gmJoIs7V4gRHfKzqcGo3AxGjpM',
    appId: '1:1092045970347:android:04c198cd0b38a90177d0ee',
    messagingSenderId: '1092045970347',
    projectId: 'attendance-36f66',
    storageBucket: 'attendance-36f66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoPuW-9kL_Ms02nfO-zfQL4Z6xYRVQbaU',
    appId: '1:1092045970347:ios:58cd2ea4865766d377d0ee',
    messagingSenderId: '1092045970347',
    projectId: 'attendance-36f66',
    storageBucket: 'attendance-36f66.appspot.com',
    iosBundleId: 'com.example.qrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoPuW-9kL_Ms02nfO-zfQL4Z6xYRVQbaU',
    appId: '1:1092045970347:ios:58cd2ea4865766d377d0ee',
    messagingSenderId: '1092045970347',
    projectId: 'attendance-36f66',
    storageBucket: 'attendance-36f66.appspot.com',
    iosBundleId: 'com.example.qrCode',
  );
}
